create game field
kolike/tetris-2023 pull request #1
Opened 2023-11-08 14:00 UTC by kolike

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const [activeCell, setActiveCell] = useState('0');
Это больше не нужно?

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Field.tsx
> +  for (let i = 0; i < 200; i++) {
200? 🤔

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Field.tsx
> +import './field.css';
Мб все таки `styled-components`? 🥲

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Field.tsx
> +    <div className="game-scope">
Этот див нужен?

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/cell.css
> +    width: 18px;
Зачем дублировал?

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  const clickme = () => {
Название вышка

2023-11-09 09:05 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  const [active, setActive] = useState(false);
А нужен ли каждой клетке тоже свой стейт, если у нас уже есть один в родительском компоненте?

2023-11-10 09:26 UTC, 0xDmitry commented on package.json
> +    "styled": "^1.0.0"
Разве либа не styled-components называется? 🤔

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
> +    line: 20,
`linesCount`

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
> +    column: 10,
`columnsCount`

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
> +  console.log(fieldSettings);
☠️

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
> +export type Settings = { cellWidth: number; line: number; column: number };
А давай в провайдер настройки ебанем 😍

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +const Form = styled.form`
Я бы назвал `Container`

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +          setFieldSettings({ ...fieldSettings, line: +e.target.value })
Брат...

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Field.tsx
> +  console.log(fieldSettings.cellWidth * fieldSettings.line);
☠️

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Field.tsx
> +    <Container>
А нужен нам этот контейнер?

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
>      <>
Это надо?

2023-11-10 09:26 UTC, 0xDmitry commented on app/page.tsx
> +      <Container>
Это надо?

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Field.tsx
> +const FieldSpace = styled.div<{ $fieldSettings: Props }>`
Давай лучше сделаем пропсы `height` и `width`

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  const [isActive, setIsActive] = useState(false);
Это потом тебе выстрелит) но можем пока так оставить, сам потом поймешь

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  fieldSettings: Settings;
cellWidth будет достаточно

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Сell.tsx
> +    setIsActive((prev) => !prev);
❤️

2023-11-10 09:26 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  };
Отступ плиз

2023-11-10 11:16 UTC, kolike commented on app/page.tsx
> +      <Container>
надо, я по нему равняю по центру свои внутренние компоненты

2023-11-10 14:25 UTC, 0xDmitry commented on package.json
> +    "styled": "^1.0.0",
А вот это можно удалить? Я хз че это такое и подозреваю, что это ломает деплой

2023-11-10 14:25 UTC, 0xDmitry commented on app/page.tsx
> +      <fieldSettingsContext.Provider
Провайдер хорошо бы в отдельный файл

2023-11-10 14:25 UTC, 0xDmitry commented on app/page.tsx
> +  setFieldSettings: (prev: any) => void;
any низя

2023-11-10 14:25 UTC, 0xDmitry commented on app/page.tsx
> +    <Container>
Так нужен этот контейнер?

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const { fieldSettings } = useSettingsContext();
давай создадим хук `useSettings` который будет сразу объект с настройками возвращать и положим туда же, где и провайдер

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Field.tsx
> +    i < fieldSettings.linesCount * fieldSettings.columnsCount;
давай их на 24 деструктурируем

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Field.tsx
> +  height: ${(props) => props.$cellWidth * props.$height}px;
тебе не надо здесь считать ширину и высоту используя `cellWidth`, передавай сразу посчитанные значения

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Field.tsx
> +  $cellWidth: number;
можно удалить

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Сell.tsx
> +const FieldCell = styled.div<{ $isActive?: boolean; $width: number }>`
лучше `$size`

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Сell.tsx
> +  cellWidth: number;
лучше `size`

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/Сell.tsx
> +      onClick={() => setActiveCell()}></FieldCell>
можно заинлайнить

2023-11-10 14:25 UTC, 0xDmitry commented on app/page.tsx
> +  cellWidth: number;
лучше `cellSize`

2023-11-10 14:25 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +
лишний отступ

2023-11-13 08:25 UTC, kolike commented on app/page.tsx
> +  setFieldSettings: (prev: any) => void;
надо разобраться с типами

2023-11-13 12:02 UTC, 0xDmitry requested changes

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const getFieldSize = (size: number) => {
Зачем эта функция? Давай заинлайним

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +
Отступ

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +      <label htmlFor="cellSize">Enter cell width</label>
size

2023-11-13 12:02 UTC, 0xDmitry commented on app/page.tsx
> +  const [fieldSettings, setFieldSettings] = useState<Settings>({
Этот стейт должен лежать в файле с провайдером

2023-11-13 12:02 UTC, 0xDmitry commented on app/page.tsx
> +      <fieldSettingsContext.Provider
Это должно быть в файле layout.tsx

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/FieldSettingsContext.tsx
> +export const UseSettings = () => {
С маленькой буквы хуки называем

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/FieldSettingsContext.tsx
> +export const fieldSettingsContext = createContext<SettingsContext>({
Тебе не надо экспортировать контекст, тебе надо экспортировать провайдер этого контекста

2023-11-13 12:02 UTC, 0xDmitry commented on app/components/FieldSettingsContext.tsx
> +
Переименуй плиз файл в FieldSettingsPtovider и положи в папочку providers

2023-11-14 13:25 UTC, 0xDmitry commented on app/layout.tsx
> +    <FieldSettingsProvider>
Давай в `body` его все-таки вставим

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/hooks/useSettings.tsx
> +export const useSettings = () => {
Да это перебор, давай в `FieldSettingsProvider.tsx` его закинем

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const getFieldSize = (size: number) => {
И?)

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +import React, { useContext } from "react";
`useContext` удали

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +
Третий раз пишу - отступ

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +      <label htmlFor="cellSize">Enter cell width</label>
size

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +interface props {
Props

2023-11-14 13:25 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +export const fieldSettingsContext = createContext<SettingsContext>({
не надо экспортировать

2023-11-14 14:11 UTC, 0xDmitry commented on app/layout.tsx
> +  children: JSX.Element | JSX.Element[];
Наоборот, здесь оставь `React.ReactNode` и в провайдере поменяй

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +import { useContext } from "react";
в начало файла

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const getFieldSize = (size: number) => {
давай заинлайним, я писал уже

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +export const useSettings = () => {
useFieldSettings

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/Field.tsx
> +};
отступ

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +
Убери отступ

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +      <label htmlFor="cellSize">Enter cell width</label>
Enter cell size

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +export interface Props {
Зачем `export`?

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/providers/FieldSettingsProvider.tsx
> +
Давай папочку `providers` вынесем из папочки `components`

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/Сell.tsx
> +};
Отступ

2023-11-14 14:11 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +};
Отступ

2023-11-15 07:47 UTC, 0xDmitry approved these changes

2023-11-15 07:47 UTC, 0xDmitry commented on app/components/Field.tsx
> +      $height={cellSize * linesCount}
❤️

2023-11-15 08:04 UTC, merged