add-micro-logic
kolike/tetris-2023 pull request #3
Opened 2023-11-24 14:04 UTC by kolike

2023-12-18 18:23 UTC, 0xDmitry requested changes

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +  }, [fieldSettings]);
заче поменял на `fieldSettings`?

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const [cubeCoord, setCubeCoord] = useState({ y: 0, x: 0 });
`activeCellCoords`

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const [cubeAtBottom, setCubeAtBottom] = useState(false);
можно избавиться от лишнего стейта и сделать вычисляемым с помощью `useMemo`

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +              y: prev.y + 1 > linesCount - 1 ? linesCount - 1 : prev.y + 1,
В прошлом варианте мы сначала просто меняли координаты, а затем проверяли вышли ли мы за границы поля и если нет, то сетили новый стейт. Хотелось бы это не менять.

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +  useEffect(() => {
давай лучше менять состояние поля там же где ты меняешь координаты активной ячейки

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> +    if (cubeCoord.y >= 19) {
почему 19?

2023-12-18 18:23 UTC, 0xDmitry commented on app/components/Field.tsx
> -
зачем убрал отступ?

2023-12-19 08:41 UTC, 0xDmitry requested changes

2023-12-19 08:41 UTC, 0xDmitry commented on app/components/Field.tsx
> +  const [activeCellCoords, setActiveCellCoords] = useState({ x: 0, y: 0 });
Разве ты с этих координат начинаешь?

2023-12-19 08:41 UTC, 0xDmitry commented on app/components/Field.tsx
> +    () => activeCellCoords.x >= linesCount - 1,
А может быть больше?

2023-12-19 08:41 UTC, 0xDmitry commented on app/components/Field.tsx
> +  }, []);
Опять спрашиваю, зачем поменял зависимости эфекта?

2023-12-19 08:41 UTC, 0xDmitry commented on app/components/Field.tsx
> +            moveBlock(1, 0);
Получается ты двигаешь свой блок не проверяя границы поля. Надо вернуть как было раньше и после успешной проверки границ менять состояние поля и координаты активной ячейки.

2023-12-19 13:53 UTC, kolike commented on app/components/Field.tsx
> +  }, []);
само поле отрисовывалось с лагами

2023-12-19 14:12 UTC, 0xDmitry commented on app/components/Field.tsx
> +  }, []);
что значит с лагами?

2023-12-19 14:12 UTC, 0xDmitry commented on app/components/Field.tsx
> +    () => activeCellCoords.x == linesCount - 1,
А почему у тебя `x` отвечает за вертикальную ось? 🤔

2023-12-19 14:12 UTC, 0xDmitry commented on app/components/Field.tsx
> +            if (activeCellCoords.x < linesCount - 1) {
Ладно, ты меня не понял, голосом обсудим

2023-12-20 13:32 UTC, 0xDmitry requested changes

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +    x: 0,
разве мы начинаем с этих координат?

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +    () => activeCellCoords.y == linesCount - 1,
`===`

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +        activeCellCoords.y,
🤔

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +      let i = activeCellCoords.x;
`newX`, `newY` будет понятнее

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +      if (!isBottom) {
давай лучше если `isBottom` выходить из функции сразу

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +            j++;
почему ты меняешь `j` по вертикали и `i` по горизонтали?

2023-12-20 13:32 UTC, 0xDmitry commented on app/components/Field.tsx
> +  }, [linesCount, columnsCount, activeCellCoords]);
`isBottom` забыл

2023-12-21 08:11 UTC, kolike commented on app/components/Field.tsx
> +            j++;
ну как же, j===newY, а если нажать "вниз", то меняется координата Y, вроде понятно

2023-12-22 09:56 UTC, 0xDmitry requested changes

2023-12-22 09:56 UTC, 0xDmitry commented on app/components/Field.tsx
> +  if (linesCount > 0 && columnsCount > 0) {
Давай лучше не будем давать пользователю вводить эти значения меньше 1

2023-12-22 09:56 UTC, 0xDmitry commented on app/components/Field.tsx
>    const [cellsState, setСellsState] = useState<boolean[][]>([]);
Раз ты `activeCellCoords` инициализируешь, то давай и этот стейт инициализируем

2023-12-22 09:56 UTC, 0xDmitry commented on app/components/Field.tsx
> +        activeCellCoords.x,
Не, тут нужно явно передовать стартовые координаты как ты делаешь ниже

2023-12-22 09:56 UTC, 0xDmitry commented on app/components/Field.tsx
> +      if (isBottom) {
Я уже писал, давай сделаем эту проверку в самом начале функции и если `true` выйдем из функции, без `else`

2023-12-22 12:14 UTC, kolike commented on app/components/Field.tsx
>    const [cellsState, setСellsState] = useState<boolean[][]>([]);
а разве он не проинициализирован пустым массивом?

2023-12-22 19:09 UTC, 0xDmitry requested changes

2023-12-22 19:09 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +          if (+e.target.value <= 0 || +e.target.value > 50) {
Почему нельзя больше 50?

2023-12-22 19:09 UTC, 0xDmitry commented on app/components/FieldSettings.tsx
> +            setFieldSettings((prev) => ({
А зачем что-то делать если пользователь ввел неподходящее число?

2023-12-22 19:09 UTC, 0xDmitry commented on app/components/Field.tsx
> +      if (!isBottom) {
Я имел в виду 

```
if (isBottom) {
  return;
}
```

И дальше твоя логика

2023-12-22 19:09 UTC, 0xDmitry commented on app/components/Field.tsx
>    const [cellsState, setСellsState] = useState<boolean[][]>([]);
Тогда давай `activeCellCoords` тоже нулями проинициализируем чтобы было симметрично

2023-12-22 19:09 UTC, 0xDmitry commented on app/components/Field.tsx
> +  if (
Этот `if` можно убрать

2023-12-25 08:37 UTC, kolike commented on app/components/FieldSettings.tsx
> +          if (+e.target.value <= 0 || +e.target.value > 50) {
ну чтобы поле не было огромным, типо разумные пределы

2023-12-25 16:26 UTC, 0xDmitry approved these changes

2023-12-26 06:29 UTC, merged