Add new cell
kolike/tetris-2023 pull request #4
Opened 2024-01-09 10:41 UTC by kolike

added logic for the appearance of a new cube and the logic for erasing a filled line

2024-01-11 12:02 UTC, 0xDmitry requested changes

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +        $color={gameOver ? "red" : ""}>
давай лучше отдельный компонент для гейм овера использовать

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +  function fillCellsField() {
что это и зачем?

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +        setGameOver((prev) => !prev);
можно просто `setGameOver(true)`

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +    if (cellsState.length >= columnsCount) {
а может быть `false` тут?

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +      if (cellsState[activeCellCoords.y + 1][activeCellCoords.x]) {
не понял условие

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +    let newX = activeCellCoords.x;
я бы это все в функцию `moveCube` перенес чтобы логику не размазывать

2024-01-11 12:02 UTC, 0xDmitry commented on app/components/Field.tsx
> +    if (cellsState.length > 2) {
🤔

2024-01-12 12:30 UTC, kolike commented on app/components/Field.tsx
> +      if (cellsState[activeCellCoords.y + 1][activeCellCoords.x]) {
Если по следующей координате по Y - true....

2024-01-12 12:32 UTC, kolike commented on app/components/Field.tsx
> +    if (cellsState.length >= columnsCount) {
может, но в массиве находится массив, а это разве не true?

2024-01-12 12:33 UTC, kolike commented on app/components/Field.tsx
> +  function fillCellsField() {
для стирания линии использовал.
Логика такая - когда строчка вся тру, я ее просто из массива методом splice удаляю и методом unshift в начало добавлял фолсы
Но так как мы меняем логику, скорее всего не понадобится

2024-03-05 12:34 UTC, merged